### ISSUE TITLE
MergeRequest Transform Presentation Drops Reviewers on BitBucket

### ISSUE THREAD

**Issue by ipcrm** [atomist/automation-client#523]
When opening a merge request from a transform:

If the target BB project has default reviewers configured they are not assigned to the opened PR the way they would be if the PR was opened via the UI.

**Comment by cdupuis** [comment]
@lievendoclo could you look at that?

**Comment by lievendoclo** [comment]
Okay.

**Comment by lievendoclo** [comment]
I'm afraid that is default behavior of the bitbucket API. We'll need to call `https://[server]/rest/default-reviewers/1.0/projects/[project]/repos/[repo]/reviewrs` in order to get the default reviewer conditions (this also needs the bitbucket id of the repo, so we'll probably need to make that call too) and set the reviewers on PR creation ourselves.

**Comment by ipcrm** [comment]
Fixed in #542
