### ISSUE TITLE
Add caching support to GitCommandGitProject

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client#58]
Fetch or pull if the repo exists rather than do a fresh clone. If it's dirty, blow it away.

**Comment by cdupuis** [comment]
Also make sure it supports concurrent access.

**Comment by jessitron** [comment]
[ ] If the user does not have the credentials to clone the repo, they should not be able to access it the cached clone.

**Comment by jessitron** [comment]
- [ ] require a fetch to be done within a certain time frame

**Comment by johnsonr** [comment]
There should be an option for in memory caching. We don't need to go to disk for small projects such as most seed repos.

**Comment by jessitron** [comment]
the next step on this is to implement auto-release of locks; that'll complete the write-caching. which may be plenty for this.
For that step, Christian suggested storing the release function on the HandlerContext, which is brilliant because then there's no extra tracking needed, we'll just have the invoker call those functions when they're done. And the release function will need to be wrapped in something that ignores calls after the first one, so it's idempotent. Easy.
The interesting bit will be the editor for the backwards-incompatible change of passing the context into the clone method.

fyi, fetching every time means that the user's creds must have read permission, so that takes care of the piggybacking-security question. also it's easier than deciding when fetch is needed.

**Comment by cdupuis** [comment]
@jessitron what is the state of this? can this be closed?

**Comment by jessitron** [comment]
This is implemented, minimally, but it is not yet the default.

The conversion script for downstream repos is close but doesn't work yet.

If this becomes urgent enough, I can complete it (and update all our clients, plus supply an update editor to other people) in a few days. It hasn't been urgent enough

**Comment by johnsonr** [comment]
This is important. We are probably cloning 6x per push _without modification_ in `github-sdm`.

**Comment by cdupuis** [comment]
Implemented in SDM
