### ISSUE TITLE
Add code coverage analysis to build

### ISSUE THREAD

**Issue by johnsonr** [atomist/automation-client#84]
Use something like Istanbul: https://www.npmjs.com/package/istanbul

**Comment by johnsonr** [comment]
Mocha

**Comment by davidecavestro** [comment]
I've played a bit with Istanbul: so far I got only a coverage report for sources used by _test_ script.
But I failed to get full coverage data, that is producing a coverage report considering the whole set of sources.

BTW I share my findings with Istanbul: 
1. as soon as I enable the _all_ property (needed for full coverage) the coverage report gets polluted with unexpected coverage for .ts files under the `build` folder.
2. tests are currently splitted into different npm scripts, so in order to get the whole project coverage we should merge data from different mocha executions. This should be feasible both using `nyc` and `remap-istanbul`, but it doesn't make sense working at it until point 1 is fixed.

**Off topic**
As a side note, while looking at jest mocha runner to fix the issue depicted above I've seen that airbnb [transitioned from Mocha/Istanbul to Jest](https://medium.com/airbnb-engineering/unlocking-test-performance-migrating-from-mocha-to-jest-2796c508ec50). Jest seems cool but switching to it implies adapting tests.

**Comment by ddgenome** [comment]
We added this and then removed it because istanbul's understanding of TypeScript was not good. Perhaps the issue was caused by .d.ts files?

That's good to know about Jest. It doesn't seem like it will address the code coverage issue, but it could help with test speed.
